using Cosmos.System;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CrystalOSAlpha.Programming
{
    class Keys
    {
        public static ConsoleKeyEx StringToKey(string key)
        {
            switch(key)
            {
                case "ConsoleKeyEx.Escape":
                    return ConsoleKeyEx.Escape;
                case "ConsoleKeyEx.F1":
                    return ConsoleKeyEx.F1;
                case "ConsoleKeyEx.F2":
                    return ConsoleKeyEx.F2;
                case "ConsoleKeyEx.F3":
                    return ConsoleKeyEx.F3;
                case "ConsoleKeyEx.F4":
                    return ConsoleKeyEx.F4;
                case "ConsoleKeyEx.F5":
                    return ConsoleKeyEx.F5;
                case "ConsoleKeyEx.F6":
                    return ConsoleKeyEx.F6;
                case "ConsoleKeyEx.F7":
                    return ConsoleKeyEx.F7;
                case "ConsoleKeyEx.F8":
                    return ConsoleKeyEx.F8;
                case "ConsoleKeyEx.F9":
                    return ConsoleKeyEx.F9;
                case "ConsoleKeyEx.F10":
                    return ConsoleKeyEx.F10;
                case "ConsoleKeyEx.F11":
                    return ConsoleKeyEx.F11;
                case "ConsoleKeyEx.F12":
                    return ConsoleKeyEx.F12;
                case "ConsoleKeyEx.Delete":
                    return ConsoleKeyEx.Delete;
                case "ConsoleKeyEx.PauseBreak":
                    return ConsoleKeyEx.PauseBreak;
                case "ConsoleKeyEx.PrintScreen":
                    return ConsoleKeyEx.PrintScreen;
                case "ConsoleKeyEx.Home":
                    return ConsoleKeyEx.Home;
                case "ConsoleKeyEx.D0":
                    return ConsoleKeyEx.D0;
                case "ConsoleKeyEx.D1":
                    return ConsoleKeyEx.D1;
                case "ConsoleKeyEx.D2":
                    return ConsoleKeyEx.D2;
                case "ConsoleKeyEx.D3":
                    return ConsoleKeyEx.D3;
                case "ConsoleKeyEx.D4":
                    return ConsoleKeyEx.D4;
                case "ConsoleKeyEx.D5":
                    return ConsoleKeyEx.D5;
                case "ConsoleKeyEx.D6":
                    return ConsoleKeyEx.D6;
                case "ConsoleKeyEx.D7":
                    return ConsoleKeyEx.D7;
                case "ConsoleKeyEx.D8":
                    return ConsoleKeyEx.D8;
                case "ConsoleKeyEx.D9":
                    return ConsoleKeyEx.D9;
                case "ConsoleKeyEx.Minus":
                    return ConsoleKeyEx.Minus;
                case "ConsoleKeyEx.Equal":
                    return ConsoleKeyEx.Equal;
                case "ConsoleKeyEx.Backspace":
                    return ConsoleKeyEx.Backspace;
                case "ConsoleKeyEx.NumLock":
                    return ConsoleKeyEx.NumLock;
                case "ConsoleKeyEx.Slash":
                    return ConsoleKeyEx.Slash;
                case "ConsoleKeyEx.NumMultiply":
                    return ConsoleKeyEx.NumMultiply;
                case "ConsoleKeyEx.NumMinus":
                    return ConsoleKeyEx.NumMinus;
                case "ConsoleKeyEx.Tab":
                    return ConsoleKeyEx.Tab;
                case "ConsoleKeyEx.Q":
                    return ConsoleKeyEx.Q;
                case "ConsoleKeyEx.W":
                    return ConsoleKeyEx.W;
                case "ConsoleKeyEx.E":
                    return ConsoleKeyEx.E;
                case "ConsoleKeyEx.R":
                    return ConsoleKeyEx.R;
                case "ConsoleKeyEx.T":
                    return ConsoleKeyEx.T;
                case "ConsoleKeyEx.Z":
                    return ConsoleKeyEx.Z;
                case "ConsoleKeyEx.U":
                    return ConsoleKeyEx.U;
                case "ConsoleKeyEx.I":
                    return ConsoleKeyEx.I;
                case "ConsoleKeyEx.O":
                    return ConsoleKeyEx.O;
                case "ConsoleKeyEx.P":
                    return ConsoleKeyEx.P;
                case "ConsoleKeyEx.LBracket":
                    return ConsoleKeyEx.LBracket;
                case "ConsoleKeyEx.RBracket":
                    return ConsoleKeyEx.RBracket;
                case "ConsoleKeyEx.Backslash":
                    return ConsoleKeyEx.Backslash;
                case "ConsoleKeyEx.A":
                    return ConsoleKeyEx.A;
                case "ConsoleKeyEx.S":
                    return ConsoleKeyEx.S;
                case "ConsoleKeyEx.D":
                    return ConsoleKeyEx.D;
                case "ConsoleKeyEx.F":
                    return ConsoleKeyEx.F;
                case "ConsoleKeyEx.G":
                    return ConsoleKeyEx.G;
                case "ConsoleKeyEx.H":
                    return ConsoleKeyEx.H;
                case "ConsoleKeyEx.J":
                    return ConsoleKeyEx.J;
                case "ConsoleKeyEx.K":
                    return ConsoleKeyEx.K;
                case "ConsoleKeyEx.L":
                    return ConsoleKeyEx.L;
                case "ConsoleKeyEx.Semicolon":
                    return ConsoleKeyEx.Semicolon;
                case "ConsoleKeyEx.Apostrophe":
                    return ConsoleKeyEx.Apostrophe;
                case "ConsoleKeyEx.Y":
                    return ConsoleKeyEx.Y;
                case "ConsoleKeyEx.X":
                    return ConsoleKeyEx.X;
                case "ConsoleKeyEx.C":
                    return ConsoleKeyEx.C;
                case "ConsoleKeyEx.V":
                    return ConsoleKeyEx.V;
                case "ConsoleKeyEx.B":
                    return ConsoleKeyEx.B;
                case "ConsoleKeyEx.N":
                    return ConsoleKeyEx.N;
                case "ConsoleKeyEx.M":
                    return ConsoleKeyEx.M;
                case "ConsoleKeyEx.Comma":
                    return ConsoleKeyEx.Comma;
                case "ConsoleKeyEx.Spacebar":
                    return ConsoleKeyEx.Spacebar;
                default:
                    return ConsoleKeyEx.NoName;
            }
        }
    }
}
